Repository nextcloud/user_retention, pull requests merged in 2020-03, with the labels that each got.

#95 support reseting of accounts of LDAP users
  js/user_retention.js
  js/user_retention.js.map
  lib/BackgroundJob/ExpireUsers.php
  lib/Settings/Admin.php
  src/views/GroupSettings.vue
Labels: 3. to review

#107 [stable18] LDAP support
  js/user_retention.js
  js/user_retention.js.map
  lib/BackgroundJob/ExpireUsers.php
  lib/Settings/Admin.php
  package-lock.json
  package.json
  src/views/GroupSettings.vue
Labels: 3. to review

#108 [stable17] LDAP support
  js/user_retention.js
  js/user_retention.js.map
  lib/BackgroundJob/ExpireUsers.php
  lib/Settings/Admin.php
  src/views/AdminSettings.vue
Labels: 3. to review

#109 Always set the creation date
  lib/BackgroundJob/ExpireUsers.php
Labels: 3. to review, backport-request, bug

#117 only delete/reset users that have logged in at least once
  README.md
  lib/BackgroundJob/ExpireUsers.php
Labels: 3. to review, bug
