Repository nextcloud/user_retention, pull requests merged in 2020-04, with the labels that each got.

#123 Ignore the discovery date when only logged in users are purged anyway
  lib/BackgroundJob/ExpireUsers.php
Labels: 3. to review, backport-request, enhancement

#126 Update npm packages
  js/user_retention.js
  js/user_retention.js.map
  package-lock.json
  package.json
Labels: 4. to release, bug

#128 Change to @nextcloud/… packages
  .eslintrc.js
  .github/workflows/lint.yml
  .github/workflows/node.yml
  babel.config.js
  composer.json
  js/user_retention.js
  js/user_retention.js.map
  package-lock.json
  package.json
  src/views/GroupSettings.vue
Labels: 3. to review

#131 improve logging
  lib/BackgroundJob/ExpireUsers.php
Labels: 4. to release, backport-request
