Repository nextcloud/user_retention, pull requests merged in 2021-11, with the labels that each got.

#390 Update npm and node engines versions
  package.json
Labels: dependencies

#394 NPM audit fix
  js/user_retention-main.js
  js/user_retention-main.js.map
  package-lock.json
Labels: 3. to review

#396 Show success and error messages on saving settings
  js/user_retention-main.js
  js/user_retention-main.js.map
  package-lock.json
  package.json
  src/views/AdminSettings.vue
Labels: 3. to review, bug

#397 Create appstore-build-publish.yml
  .github/workflows/appstore-build-publish.yml
  Makefile
Labels: backport-request
