Repository nextcloud/user_retention, pull requests merged in 2022-08, with the labels that each got.

#450 Updating dependabot-approve-merge.yml workflow from template
  .github/workflows/dependabot-approve-merge.yml
Labels: dependencies

#451 Cleanup
  js/user_retention-main.js
  js/user_retention-main.js.map
  package-lock.json
  package.json
  src/views/AdminSettings.vue
Labels: 4. to release

#453 Update npm and node engines versions
  package.json
Labels: dependencies

#454 Log when expired users do not get deleted
  lib/BackgroundJob/ExpireUsers.php
Labels: 3. to review
