Repository nextcloud/user_retention, pull requests merged in 2023-05, with the labels that each got.

#540 Add static PHP code analysis via psalm
  .github/workflows/psalm.yml
  .github/workflows/update-nextcloud-ocp-matrix.yml
  Makefile
  composer.json
  composer.lock
  lib/AppInfo/Application.php
  lib/Service/RetentionService.php
  lib/Settings/Admin.php
  psalm.xml
  tests/psalm-baseline.xml
  tests/stub.phpstub
Labels: 3. to review, technical debt

#542 Rename default Git branch to main
  .github/workflows/update-nextcloud-ocp-matrix.yml
  Makefile
  appinfo/info.xml
Labels: 3. to review, technical debt

#546 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#547 Add simple Cypress test for admin settings
  .eslintrc.js
  .github/workflows/cypress.yml
  cypress.config.js
  cypress/e2e/settings.spec.js
  cypress/runLocal.sh
  cypress/support/commands.js
  cypress/support/e2e.js
  cypress/utils/index.js
  js/user_retention-main.js
  js/user_retention-main.js.LICENSE.txt
  js/user_retention-main.js.map
  package-lock.json
  package.json
  src/views/AdminSettings.vue
Labels: 3. to review, tests

#551 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#552 fix(package): Ignore cypress artefacts
  .gitignore
  Makefile
Labels: 3. to review, bug
