Repository nextcloud/user_retention, pull requests merged in 2023-11, with the labels that each got.

#626 fix(deps): Update NPM dependencies
  package-lock.json
Labels: 3. to review, technical debt, dependencies

#628 fix(frontend): Migrate from NcMultiselect to NcSelect
  package-lock.json
  package.json
  src/views/AdminSettings.vue
Labels: 3. to review, technical debt

#629 chore(ci): Update Github workflows from templates
  .github/workflows/appstore-build-publish.yml
  .github/workflows/cypress.yml
  .github/workflows/lint-eslint-when-unrelated.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node-when-unrelated.yml
  .github/workflows/node.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/phpunit-summary-when-unrelated.yml
  .github/workflows/pr-feedback.yml
  .github/workflows/psalm.yml
  .github/workflows/update-nextcloud-ocp-matrix.yml
Labels: technical debt, tests

#627 feat(release): Prepare 1.11.0 release with Nextcloud 28 support
  CHANGELOG.md
  appinfo/info.xml
  composer.json
  composer.lock
Labels: 3. to review

#633 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
