Repository nextcloud/user_retention, pull requests merged in 2025-06, with the labels that each got.

#876 [main] Update nextcloud/ocp dependency
  composer.lock
  tests/bootstrap.php
Labels: 3. to review, dependencies

#877 ci: update node.yml workflow from template
  .github/workflows/appstore-build-publish.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/pr-feedback.yml
  .github/workflows/psalm-matrix.yml
  .github/workflows/reuse.yml
  .github/workflows/update-nextcloud-ocp-approve-merge.yml
  .github/workflows/update-nextcloud-ocp-matrix.yml
  cypress/e2e/settings.spec.js
Labels: dependencies

#879 ci: Update PHPUnit to 10 and Psalm to 6.12
  .gitignore
  composer.json
  lib/AppInfo/Application.php
  lib/BackgroundJob/ExpireUsers.php
  lib/Listeners/UserChangedListener.php
  lib/Settings/Admin.php
  psalm.xml
  tests/Listeners/UserChangedListenerTest.php
  tests/Service/RetentionServiceTest.php
  tests/phpunit.xml
  tests/psalm-baseline.xml
  vendor-bin/phpunit/composer.json
  vendor-bin/phpunit/composer.lock
  vendor-bin/psalm/composer.json
  vendor-bin/psalm/composer.lock
Labels: 3. to review, technical debt, tests
